import React from "react";
import Head from "next/head";
import styles from "../styles/Layout.module.css";
import Navbar from "./Navbar";

export default function Layout({ children, home }) {
  return (
    <React.Fragment>
      <Head>
        <title>Next React App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Navbar />
        <main>{children}</main>
      </div>
    </React.Fragment>
  );
}
